<?php declare(strict_types=1);

namespace Aero\MasterAds\Tests\Properties;

use Aero\MasterAds\Models\AiProvider;
use Aero\MasterAds\Models\MetaAccount;
use Aero\MasterAds\Models\Workspace;
use Backend\Models\User as BackendUser;
use DB;
use PluginTestCase;

/**
 * Property P6 — Token Confidentiality.
 *
 * For every {@see MetaAccount} and {@see AiProvider}, the plugin MUST
 * guarantee two invariants over any randomly chosen secret value:
 *
 *   1. Serialisation safety: `$model->toArray()` (and any downstream JSON
 *      payload built from it) MUST NOT expose the secret attribute(s) —
 *      i.e. `access_token` / `refresh_token` for {@see MetaAccount},
 *      `api_key` for {@see AiProvider}.
 *
 *   2. Encryption at rest: the raw value persisted in the database column
 *      MUST differ from the plaintext provided by the caller — the model
 *      mutator wraps it with `Crypt::encrypt` before persisting, and the
 *      accessor decrypts it transparently on read.
 *
 * The property is checked over N = 50 random ASCII tokens of length
 * 32–256 generated by {@see self::tokenProvider()}. Both invariants must
 * hold for every single token; a single counter-example breaks the
 * property.
 *
 * Validates: Property P6 / Requirements 2.2, 2.3, 5.3, 15.1, 15.3.
 */
class TokenConfidentialityTest extends PluginTestCase
{
    /**
     * Number of distinct random tokens generated by the data provider for
     * each parameterised test. Increase to widen the search space; keep
     * small enough that the suite remains fast (each iteration boots a
     * fresh DB row + Workspace).
     */
    private const TOKEN_SAMPLE_SIZE = 50;

    /**
     * Monotonically-increasing counter used to mint unique slugs / Meta
     * act-ids across data-provider iterations so unique-index constraints
     * (`workspaces.slug`, `(workspace_id, meta_act_id)`) do not collide.
     */
    private static int $sequence = 0;

    /**
     * Generate {@see self::TOKEN_SAMPLE_SIZE} random tokens — printable
     * ASCII, length uniformly chosen in [32, 256] — and yield each as a
     * single-argument dataset row.
     *
     * Charset deliberately excludes raw control / quote characters so the
     * tokens survive any logging or shell-style escaping without altering
     * the property under test; the encryption invariant is independent of
     * the alphabet used.
     *
     * @return iterable<int, array{0: string}>
     */
    public static function tokenProvider(): iterable
    {
        $chars = '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ-_.~';
        $alphabetSize = strlen($chars);

        for ($i = 0; $i < self::TOKEN_SAMPLE_SIZE; $i++) {
            $len = random_int(32, 256);
            $token = '';
            for ($j = 0; $j < $len; $j++) {
                $token .= $chars[random_int(0, $alphabetSize - 1)];
            }
            yield [$token];
        }
    }

    /**
     * Property P6 over {@see MetaAccount}.
     *
     * Given an arbitrary plaintext token, persisting it as both
     * `access_token` and `refresh_token` on a freshly-created Meta account:
     *
     *   - `toArray()` MUST omit both columns (driven by `$hidden`).
     *   - Reloading via `MetaAccount::find()` MUST round-trip the original
     *     plaintext through the decryption accessor.
     *   - The raw column value in the database MUST differ from the
     *     plaintext — proving the value at rest is the encrypted payload,
     *     not the secret itself.
     *
     * @dataProvider tokenProvider
     */
    public function testMetaAccountTokenConfidentiality(string $token): void
    {
        $workspace = $this->createWorkspace();

        $account = new MetaAccount();
        $account->workspace_id = $workspace->id;
        $account->meta_act_id  = 'act_' . self::nextSequence();
        $account->currency     = 'USD';
        $account->access_token = $token;
        $account->refresh_token = $token;
        $account->save();

        // ── Invariant 1: serialisation safety ─────────────────────────
        $array = $account->toArray();
        $this->assertFalse(
            array_key_exists('access_token', $array),
            'MetaAccount::toArray() must not expose access_token'
        );
        $this->assertFalse(
            array_key_exists('refresh_token', $array),
            'MetaAccount::toArray() must not expose refresh_token'
        );

        // ── Round-trip via accessor (decryption recovers plaintext) ───
        $reloaded = MetaAccount::withoutGlobalScopes()->find($account->id);
        $this->assertNotNull($reloaded, 'MetaAccount must be re-fetchable by id');
        $this->assertSame(
            $token,
            $reloaded->access_token,
            'access_token accessor must decrypt back to the original plaintext'
        );
        $this->assertSame(
            $token,
            $reloaded->refresh_token,
            'refresh_token accessor must decrypt back to the original plaintext'
        );

        // ── Invariant 2: encryption at rest ───────────────────────────
        $rawAccess = DB::table('aero_masterads_meta_accounts')
            ->where('id', $account->id)
            ->value('access_token');
        $rawRefresh = DB::table('aero_masterads_meta_accounts')
            ->where('id', $account->id)
            ->value('refresh_token');

        $this->assertNotSame(
            $token,
            $rawAccess,
            'access_token raw DB value must differ from plaintext (must be encrypted)'
        );
        $this->assertNotSame(
            $token,
            $rawRefresh,
            'refresh_token raw DB value must differ from plaintext (must be encrypted)'
        );
    }

    /**
     * Property P6 over {@see AiProvider}.
     *
     * Given an arbitrary plaintext token used as an LLM `api_key`:
     *
     *   - `toArray()` MUST omit `api_key` (driven by `$hidden`).
     *   - Reloading via `AiProvider::find()` MUST round-trip the original
     *     plaintext through the decryption accessor.
     *   - The raw column value in the database MUST differ from the
     *     plaintext — the mutator wraps it in `Crypt::encrypt`.
     *
     * @dataProvider tokenProvider
     */
    public function testAiProviderApiKeyConfidentiality(string $token): void
    {
        $workspace = $this->createWorkspace();

        $provider = new AiProvider();
        $provider->workspace_id = $workspace->id;
        $provider->name         = 'Test Provider ' . self::nextSequence();
        $provider->driver       = 'openrouter';
        $provider->model        = 'anthropic/claude-3.5-sonnet';
        $provider->api_key      = $token;
        $provider->is_default   = false;
        $provider->save();

        // ── Invariant 1: serialisation safety ─────────────────────────
        $array = $provider->toArray();
        $this->assertFalse(
            array_key_exists('api_key', $array),
            'AiProvider::toArray() must not expose api_key'
        );

        // ── Round-trip via accessor ───────────────────────────────────
        $reloaded = AiProvider::withoutGlobalScopes()->find($provider->id);
        $this->assertNotNull($reloaded, 'AiProvider must be re-fetchable by id');
        $this->assertSame(
            $token,
            $reloaded->api_key,
            'api_key accessor must decrypt back to the original plaintext'
        );

        // ── Invariant 2: encryption at rest ───────────────────────────
        $raw = DB::table('aero_masterads_ai_providers')
            ->where('id', $provider->id)
            ->value('api_key');

        $this->assertNotSame(
            $token,
            $raw,
            'api_key raw DB value must differ from plaintext (must be encrypted)'
        );
    }

    /**
     * Create a fresh, fully-valid {@see Workspace} backed by a brand-new
     * Backend user — the `owner_id` FK is required and constrained against
     * `backend_users`. Slug derives from a monotonic counter so the unique
     * index survives being driven 50× per test method by the data provider.
     */
    protected function createWorkspace(): Workspace
    {
        $seq = self::nextSequence();
        // alpha_dash-safe unique tag: uniqid() returns a 13-char hex string,
        // and we replace any dot from `more_entropy` with a dash so the slug
        // validator (`alpha_dash`) on Workspace accepts it.
        $unique = str_replace('.', '-', uniqid('', true));

        $owner = BackendUser::create([
            'login'                 => 'p6_owner_' . $seq,
            'email'                 => 'p6_owner_' . $unique . '@example.test',
            'password'              => 'secret123',
            'password_confirmation' => 'secret123',
            'first_name'            => 'P6',
            'last_name'             => 'Owner',
        ]);

        return Workspace::create([
            'name'     => 'P6 Workspace ' . $seq,
            'slug'     => 'p6-ws-' . $seq . '-' . $unique,
            'owner_id' => $owner->id,
        ]);
    }

    /**
     * Return the next value of a process-local monotonic counter; used to
     * mint unique slugs / Meta act-ids across data-provider rows.
     */
    private static function nextSequence(): int
    {
        return ++self::$sequence;
    }
}
